// Render the Reeves duck SVG to Unicode block art at four sizes using chafa.
// Writes src/tui/brand/duck-rendered.ts with embedded ANSI strings.
// Run after editing src/tui/brand/assets/duck.svg.

import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = join(root, 'src/tui/brand/assets/duck.svg')
const target = join(root, 'src/tui/brand/duck-rendered.ts')
const sourceSvg = readFileSync(source, 'utf8')

const variants = {
  hero:     { w: 20, h: 10 },
  single:   { w: 14, h: 7 },
  duckling: { w: 8,  h: 4 },
  mini:     { w: 4,  h: 2 },
}

function shiftedSvgPath(dy) {
  const dir = mkdtempSync(join(tmpdir(), 'reeves-duck-'))
  const path = join(dir, 'duck.svg')
  const svg = sourceSvg
    .replace(/(<svg\b[^>]*>)/, `$1\n  <g transform="translate(0 ${dy})">`)
    .replace(/<\/svg>\s*$/, '  </g>\n</svg>')
  writeFileSync(path, svg, 'utf8')
  return { dir, path }
}

function render(width, height, shiftRows = 0) {
  let cleanupDir = ''
  let input = source
  if (shiftRows > 0) {
    const shifted = shiftedSvgPath((48 / height) * shiftRows)
    cleanupDir = shifted.dir
    input = shifted.path
  }
  const out = execFileSync('chafa', [
    '--symbols', 'block',
    '--size', `${width}x${height}`,
    '--format', 'symbols',
    '--colors', '256',
    '--fg-only',
    input,
  ], { encoding: 'utf8' })
  if (cleanupDir) rmSync(cleanupDir, { recursive: true, force: true })
  // Strip the show/hide cursor wrappers chafa adds. Drop the trailing newline.
  return out.replace(/\[\?25[lh]/g, '').replace(/\n$/, '')
}

const rendered = Object.fromEntries(
  Object.entries(variants).map(([name, { w, h }]) => [name, render(w, h)]),
)
const halfDownRendered = Object.fromEntries(
  Object.entries(variants).map(([name, { w, h }]) => [`${name}HalfDown`, render(w, h, 0.5)]),
)
const downRendered = Object.fromEntries(
  Object.entries(variants).map(([name, { w, h }]) => [`${name}Down`, render(w, h, 1)]),
)
const allRendered = { ...rendered, ...halfDownRendered, ...downRendered }

const body = `// Auto-generated by scripts/render-mascot.mjs from src/tui/brand/assets/duck.svg.
// Do not hand-edit. Re-run \`node scripts/render-mascot.mjs\` after changing the SVG.

export const DUCK_RENDERED = {
  hero:     ${JSON.stringify(allRendered.hero)},
  single:   ${JSON.stringify(allRendered.single)},
  duckling: ${JSON.stringify(allRendered.duckling)},
  mini:     ${JSON.stringify(allRendered.mini)},
  heroHalfDown:     ${JSON.stringify(allRendered.heroHalfDown)},
  singleHalfDown:   ${JSON.stringify(allRendered.singleHalfDown)},
  ducklingHalfDown: ${JSON.stringify(allRendered.ducklingHalfDown)},
  miniHalfDown:     ${JSON.stringify(allRendered.miniHalfDown)},
  heroDown:     ${JSON.stringify(allRendered.heroDown)},
  singleDown:   ${JSON.stringify(allRendered.singleDown)},
  ducklingDown: ${JSON.stringify(allRendered.ducklingDown)},
  miniDown:     ${JSON.stringify(allRendered.miniDown)},
} as const

export type DuckVariant = keyof typeof DUCK_RENDERED
`

writeFileSync(target, body, 'utf8')
console.log(`wrote ${target}`)
