import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const clientRoot = join(process.cwd(), 'src/web/client')

function readClientFile(name: string): string {
  return readFileSync(join(clientRoot, name), 'utf8')
}

describe('web client create flow', () => {
  it('mounts the animated Lottie duck instead of the old inline SVG', () => {
    const html = readClientFile('index.html')
    const js = readClientFile('app.js')
    const css = readClientFile('app.css')
    const lottie = JSON.parse(readClientFile('brand-duck.json')) as { nm?: string; layers?: unknown[]; assets?: unknown[] }

    expect(html).toContain('id="brand-duck"')
    expect(html).not.toContain('<svg class="brand-duck"')
    expect(js).toContain("api('GET', '/brand-duck.json')")
    expect(js).toContain('window.requestAnimationFrame(tick)')
    expect(js).toContain('function renderBrandDuck(animation)')
    expect(css).toContain('.brand-duck svg')
    expect(lottie.nm).toBe('chick1 ')
    expect(lottie.layers?.length).toBeGreaterThan(0)
    expect(lottie.assets?.length).toBeGreaterThan(0)
  })

  it('keeps new run and add agent as separate entry points', () => {
    const html = readClientFile('index.html')
    const js = readClientFile('app.js')

    expect(html).toContain('id="new-run-btn"')
    expect(html).toContain('id="new-agent-btn"')
    expect(html).toContain('id="doctor-btn"')
    expect(html).toContain('id="doctor-dialog"')
    expect(html).toContain('id="about-btn"')
    expect(html).toContain('id="about-dialog"')
    expect(html).toContain('id="language-select"')
    expect(html).toContain('id="empty-new-run"')
    expect(html).toContain('id="stage-add-agent"')
    expect(html).toContain('id="create-run-tab"')
    expect(html).toContain('id="create-agent-tab"')
    expect(html).toContain('id="f-agent-run"')
    expect(html).toContain('id="provider-grid"')
    expect(html).toContain('id="f-model"')
    expect(html).toContain('id="f-permissions"')
    expect(html).toContain('id="permission-grid"')
    expect(html).toContain('class="field-help"')
    expect(html).toContain('id="run-name-help"')
    expect(html).toContain('id="provider-help"')
    expect(html).toContain('Permission mode')
    expect(html).toContain('Add agent')
    expect(html).not.toContain('id="new-btn"')
    expect(html).not.toContain('id="f-run"')
    expect(html).not.toContain('Target run')

    expect(js).toContain('function openRunDialog()')
    expect(js).toContain('function openAgentDialog(runId)')
    expect(js).toContain('function populateAgentRunSelect(preferred)')
    expect(js).toContain('function updateProviderSelection()')
    expect(js).toContain('function handleProviderKeydown(ev, providerId)')
    expect(js).toContain('function renderModels()')
    expect(js).toContain('function updatePermissionSelection()')
    expect(js).toContain('function handlePermissionKeydown(ev)')
    expect(js).toContain('function updateCreateSubmitState()')
    expect(js).toContain('function showUnavailableAgent(id, found)')
    expect(js).toContain('function reconcileSelectedAgent()')
    expect(js).toContain('function reconcileCreateDialog()')
    expect(js).toContain('function renderLanguageSelect()')
    expect(js).toContain("api('POST', '/api/language'")
    expect(js).toContain("api('POST', `/api/history/${encodeURIComponent(record.id)}/delete`")
    expect(js).toContain("api('POST', `/api/runs/${encodeURIComponent(run.id)}/delete`")
    expect(js).toContain("api('POST', `/api/terminals/${encodeURIComponent(agent.id)}/delete`")
    expect(js).toContain('function deleteHistoryRecord(record)')
    expect(js).toContain('function deleteAgentRecord(agent)')
    expect(js).toContain('function renderApproval(approval)')
    expect(js).toContain('function resolveApproval(approval, decision)')
    expect(js).toContain("api('POST', `/api/approvals/${encodeURIComponent(approval.id)}/resolve`")
    expect(js).toContain("task.className = 'card-task'")
    expect(js).toContain('function openDoctorDialog()')
    expect(js).toContain('function renderDoctorChecks(checks)')
    expect(js).toContain("api('GET', '/api/doctor')")
    expect(js).toContain('function openAboutDialog()')
    expect(js).toContain("createContext = { kind: 'run', runId: '' }")
    expect(js).toContain("createContext = { kind: 'agent', runId: run.id }")
    expect(js).toContain('model: el.fModel.value')
    expect(js).toContain('permissions: el.fPermissions.value')
    expect(js).toContain("run_id: createContext.kind === 'agent' ? createContext.runId : undefined")
    expect(js).toContain("run_name: createContext.kind === 'run' ?")
    expect(js).toContain("availability.className = 'card-open-hint'")
    expect(js).toContain("agent.canAttach ? t('web.openAgent') : disabledReasonLabel(agent)")
    expect(js).toContain('if (found && found.terminal.canAttach) attach(created.id)')
    expect(js).toContain('reconcileSelectedAgent()')
    expect(js).toContain('reconcileCreateDialog()')
    expect(js).toContain("'web.noLiveTmuxTarget': 'run tmux session is unavailable'")
    expect(js).toContain("ws.onclose = () => { if (session && session.id === id && !finalState)")
  })

  it('keeps polished mobile button styles scoped to the top bar', () => {
    const css = readClientFile('app.css')

    expect(css).toContain('@keyframes fadeUp')
    expect(css).toContain('@keyframes dialogIn')
    expect(css).toContain('.run-action')
    expect(css).toContain('.run-delete')
    expect(css).toContain('.card-agent-action')
    expect(css).toContain('.card-open-hint')
    expect(css).toContain('.dialog-note')
    expect(css).toContain('.field-help')
    expect(css).toContain('.provider-grid')
    expect(css).toContain('.language-picker')
    expect(css).toContain('.history-delete')
    expect(css).toContain('.approval-card')
    expect(css).toContain('.approval-approve')
    expect(css).toContain('.card-task')
    expect(css).toContain('.doctor-check')
    expect(css).toContain('.about-row')
    expect(css).toContain('.provider-option[aria-selected="true"]')
    expect(css).toContain('.create-options-grid')
    expect(css).toContain('.permission-option[aria-checked="true"]')
    expect(css).not.toContain('.topbar .btn-accent {\n    position: absolute;')
  })

  it('exposes the agent control (MCP installer) surface', () => {
    const html = readClientFile('index.html')
    const js = readClientFile('app.js')
    const css = readClientFile('app.css')

    expect(html).toContain('id="agent-control-btn"')
    expect(html).toContain('id="mcp-dialog"')
    expect(html).toContain('id="mcp-host-list"')
    expect(html).toContain('id="mcp-attach-all"')

    expect(js).toContain("api('GET', '/api/mcp-hosts')")
    expect(js).toContain("api('POST', '/api/mcp-hosts/attach'")
    expect(js).toContain("api('POST', '/api/mcp-hosts/detach'")
    expect(js).toContain("api('POST', '/api/mcp-hosts/attach-all'")
    expect(js).toContain('function renderMcpHosts()')
    expect(js).toContain('function openMcpDialog()')
    expect(js).toContain("'web.mcpTitle': 'Agent control'")

    expect(css).toContain('.mcp-host-row')
    expect(css).toContain('.mcp-host-action')
  })

  it('exposes the launch knobs, config panel, and presets panel', () => {
    const html = readClientFile('index.html')
    const js = readClientFile('app.js')

    expect(html).toContain('id="f-auth-mode"')
    expect(html).toContain('id="f-effort"')
    expect(html).toContain('id="auth-mode-field"')
    expect(html).toContain('id="effort-field"')
    expect(html).toContain('id="config-btn"')
    expect(html).toContain('id="config-dialog"')
    expect(html).toContain('id="config-list"')
    expect(html).toContain('id="presets-btn"')
    expect(html).toContain('id="presets-dialog"')
    expect(html).toContain('id="presets-list"')
    expect(html).toContain('id="preset-name-input"')

    expect(js).toContain('auth_mode: el.fAuthMode.value')
    expect(js).toContain('effort: el.fEffort.value')
    expect(js).toContain('function updateLaunchKnobVisibility()')
    expect(js).toContain('function openConfigDialog()')
    expect(js).toContain('function renderConfigFields(payload)')
    expect(js).toContain('function saveConfig()')
    expect(js).toContain("api('GET', '/api/config')")
    expect(js).toContain("api('POST', '/api/config'")
    expect(js).toContain('function openPresetsDialog()')
    expect(js).toContain('function renderPresets(presets)')
    expect(js).toContain('function savePreset()')
    expect(js).toContain("api('GET', '/api/presets')")
    expect(js).toContain("api('POST', '/api/presets/save'")
    expect(js).toContain("api('POST', `/api/presets/${encodeURIComponent(name)}/start`")
    expect(js).toContain("api('POST', `/api/presets/${encodeURIComponent(name)}/delete`")
  })
})
